// Admin Dashboard Dummy Data

export const ADMIN_STATS = [
  {
    id: "users",
    label: "Total Users",
    value: "2,847",
    raw: 2847,
    change: "+12.4%",
    trend: "up",
    icon: "users",
    color: "violet",
  },
  {
    id: "revenue",
    label: "Revenue",
    value: "$48,295",
    raw: 48295,
    change: "+8.2%",
    trend: "up",
    icon: "dollar",
    color: "emerald",
  },
  {
    id: "sessions",
    label: "Active Sessions",
    value: "342",
    raw: 342,
    change: "-3.1%",
    trend: "down",
    icon: "activity",
    color: "blue",
  },
  {
    id: "growth",
    label: "Growth Rate",
    value: "24.5%",
    raw: 24.5,
    change: "+4.7%",
    trend: "up",
    icon: "trending",
    color: "amber",
  },
];

export const MONTHLY_REVENUE = [
  { month: "Jan", value: 12500 },
  { month: "Feb", value: 18200 },
  { month: "Mar", value: 15800 },
  { month: "Apr", value: 22400 },
  { month: "May", value: 19600 },
  { month: "Jun", value: 28900 },
  { month: "Jul", value: 31200 },
  { month: "Aug", value: 26800 },
  { month: "Sep", value: 34500 },
  { month: "Oct", value: 38200 },
  { month: "Nov", value: 42100 },
  { month: "Dec", value: 48295 },
];

export const RECENT_ACTIVITY = [
  {
    id: 1,
    user: "Alice Johnson",
    action: "Created invoice #INV-2024-089",
    time: "2 min ago",
    avatar: "A",
    type: "invoice",
  },
  {
    id: 2,
    user: "Bob Smith",
    action: "Upgraded to Pro plan",
    time: "15 min ago",
    avatar: "B",
    type: "upgrade",
  },
  {
    id: 3,
    user: "Carol White",
    action: "Downloaded PDF invoice",
    time: "1 hr ago",
    avatar: "C",
    type: "download",
  },
  {
    id: 4,
    user: "David Lee",
    action: "Updated account settings",
    time: "3 hr ago",
    avatar: "D",
    type: "settings",
  },
  {
    id: 5,
    user: "Emma Davis",
    action: "Registered new account",
    time: "5 hr ago",
    avatar: "E",
    type: "signup",
  },
  {
    id: 6,
    user: "Frank Brown",
    action: "Created invoice #INV-2024-088",
    time: "1 day ago",
    avatar: "F",
    type: "invoice",
  },
  {
    id: 7,
    user: "Grace Kim",
    action: "Reset password successfully",
    time: "1 day ago",
    avatar: "G",
    type: "security",
  },
];

export const DUMMY_USERS = [
  {
    id: "u1",
    name: "Alice Johnson",
    email: "alice@example.com",
    role: "admin",
    status: "active",
    joined: "2024-01-15",
    invoices: 24,
    avatar: "A",
  },
  {
    id: "u2",
    name: "Bob Smith",
    email: "bob@example.com",
    role: "customer",
    status: "active",
    joined: "2024-02-20",
    invoices: 12,
    avatar: "B",
  },
  {
    id: "u3",
    name: "Carol White",
    email: "carol@example.com",
    role: "customer",
    status: "active",
    joined: "2024-03-05",
    invoices: 8,
    avatar: "C",
  },
  {
    id: "u4",
    name: "David Lee",
    email: "david@example.com",
    role: "customer",
    status: "inactive",
    joined: "2024-03-18",
    invoices: 3,
    avatar: "D",
  },
  {
    id: "u5",
    name: "Emma Davis",
    email: "emma@example.com",
    role: "customer",
    status: "active",
    joined: "2024-04-02",
    invoices: 19,
    avatar: "E",
  },
  {
    id: "u6",
    name: "Frank Brown",
    email: "frank@example.com",
    role: "customer",
    status: "active",
    joined: "2024-04-10",
    invoices: 7,
    avatar: "F",
  },
  {
    id: "u7",
    name: "Grace Kim",
    email: "grace@example.com",
    role: "customer",
    status: "inactive",
    joined: "2024-04-15",
    invoices: 0,
    avatar: "G",
  },
  {
    id: "u8",
    name: "Henry Wilson",
    email: "henry@example.com",
    role: "customer",
    status: "active",
    joined: "2024-04-22",
    invoices: 31,
    avatar: "H",
  },
  {
    id: "u9",
    name: "Iris Chen",
    email: "iris@example.com",
    role: "customer",
    status: "active",
    joined: "2024-05-01",
    invoices: 15,
    avatar: "I",
  },
  {
    id: "u10",
    name: "Jack Taylor",
    email: "jack@example.com",
    role: "customer",
    status: "active",
    joined: "2024-05-08",
    invoices: 4,
    avatar: "J",
  },
  {
    id: "u11",
    name: "Karen Moore",
    email: "karen@example.com",
    role: "customer",
    status: "inactive",
    joined: "2024-05-15",
    invoices: 2,
    avatar: "K",
  },
  {
    id: "u12",
    name: "Liam Anderson",
    email: "liam@example.com",
    role: "customer",
    status: "active",
    joined: "2024-05-20",
    invoices: 9,
    avatar: "L",
  },
];
